[deps]
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
CacheVariables = "9a355d7c-ffe9-11e8-019f-21dae27d1722"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
